language: node_js
node_js:
  - 12.14.1
cache:
  directories:
    - node_modules
script:
  # - npm test
  # - npm run build
  - echo "skipping test and build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  # local_dir: build
  verbose: true
  on:
    branch: main
